#ifndef CONSTANTS_H__
#define CONSTANTS_H__

#define MAX_INTEGER_LENGTH 40
#define MAX_MANTISS_LENGTH 40
#define MAX_EXPONENT_LENGTH 5
#define TOTAL_DECIMAL_LENGTH (MAX_MANTISS_LENGTH + MAX_EXPONENT_LENGTH + 3)
#define MAX_EXPONENT_VALUE 99999

typedef int error;

enum input_errors {
    WRONG_INTEGER_INPUT = 1,
    WRONG_DECIMAL_INPUT = 2,
    NOT_A_NUMBER_INPUT = 3,
    WRONG_SIGN = 4,
    DIVISION_BY_ZERO = 5,
    EXPONENT_OVERFLOW = 6,
    EXPONENT_UNDERFLOW = 7
};

#endif
